exports.BLOG = "/blog"
exports.HOME = "/"
exports.TEAMS = "/team"
exports.PROJECTS = "/projects"
exports.WORK_WITH_US = "/work-with-us"
exports.CONTACT = "/contact-us"
exports.ABOUT = "/about-us"
exports.PRIVACY_POLICY = "/privacy-policy"