exports.HOME = "/"
exports.ABOUT = "/about-us"
exports.PROJECTS = "/projects"
exports.SERVICES = "/services"
exports.BLOG = "/blog"
exports.WORK_WITH_US = "/work-with-us"
exports.CONTACT = "/contact-us"
exports.PRIVACY_POLICY = "/privacy-policy"
exports.TEAMS = "/team"
exports.REFERENCES = "/references"
exports.FAQ = "/faq"
exports.PRUEBA = "/prueba"
exports.SITEMAP = "/x-default-sitemap-0.xml"


